import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../app/theme.dart';
import '../../room_management/domain/room_model.dart';
import '../../room_management/presentation/room_controller.dart';
import '../../shared_widgets/app_button.dart';
import '../../shared_widgets/app_text_field.dart';

class CheckInModal extends ConsumerStatefulWidget {
  final RoomModel room;

  const CheckInModal({super.key, required this.room});

  @override
  ConsumerState<CheckInModal> createState() => _CheckInModalState();
}

class _CheckInModalState extends ConsumerState<CheckInModal> {
  final _formKey = GlobalKey<FormState>();

  String _bookingSource = 'WALK_IN'; // 'WALK_IN' or 'REDDOORZ'
  final _bookingCodeController = TextEditingController();
  final _nikController = TextEditingController();
  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _phoneController = TextEditingController();
  late TextEditingController _priceController;

  int _totalNights = 1;
  bool _isManualPrice = false;
  String _paymentMethod = 'CASH'; // CASH, QRIS, TRANSFER, REDDOORZ_PREPAID

  bool _isOcrLoading = false;
  bool _isOcrExtracted = false;
  double _ocrConfidence = 0.0;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _priceController = TextEditingController(
      text: (widget.room.basePricePerNight * _totalNights).toInt().toString(),
    );
    if (_bookingSource == 'REDDOORZ') {
      _paymentMethod = 'REDDOORZ_PREPAID';
    }
  }

  @override
  void dispose() {
    _bookingCodeController.dispose();
    _nikController.dispose();
    _nameController.dispose();
    _addressController.dispose();
    _phoneController.dispose();
    _priceController.dispose();
    super.dispose();
  }

  void _setNights(int nights) {
    if (nights < 1) return;
    setState(() {
      _totalNights = nights;
      if (!_isManualPrice) {
        _priceController.text = (widget.room.basePricePerNight * _totalNights).toInt().toString();
      }
    });
  }

  void _resetPriceToStandard() {
    setState(() {
      _isManualPrice = false;
      _priceController.text = (widget.room.basePricePerNight * _totalNights).toInt().toString();
    });
  }

  double get _currentEffectiveTotal {
    final parsed = double.tryParse(_priceController.text.replaceAll(RegExp(r'[^0-9]'), ''));
    if (parsed != null && parsed > 0) {
      return parsed;
    }
    return widget.room.basePricePerNight * _totalNights;
  }

  // Simulate Google Cloud Vision OCR Extraction
  Future<void> _simulateOcrScan() async {
    setState(() {
      _isOcrLoading = true;
      _errorMessage = null;
    });

    // Simulate 1.2s OCR processing (under 3s NFR limit)
    await Future.delayed(const Duration(milliseconds: 1200));

    // Sample data generated by OCR
    final sampleGuests = [
      {
        'nik': '3578012409890002',
        'name': 'BAMBANG PRASETYO',
        'address': 'JL. DIPONEGORO NO. 45, SURABAYA',
        'phone': '081298765432',
        'confidence': 0.94,
      },
      {
        'nik': '3171051508920004',
        'name': 'DEWI KARTIKA SARI',
        'address': 'JL. GATOT SUBROTO KAV. 18, JAKARTA',
        'phone': '085612349876',
        'confidence': 0.91,
      },
      {
        'nik': '3273024806870001',
        'name': 'AHMAD FAUZI',
        'address': 'JL. ASIA AFRIKA NO. 110, BANDUNG',
        'phone': '087812908765',
        'confidence': 0.96,
      },
    ];

    final picked = sampleGuests[DateTime.now().second % sampleGuests.length];

    setState(() {
      _isOcrLoading = false;
      _isOcrExtracted = true;
      _nikController.text = picked['nik'] as String;
      _nameController.text = picked['name'] as String;
      _addressController.text = picked['address'] as String;
      if (_phoneController.text.isEmpty) {
        _phoneController.text = picked['phone'] as String;
      }
      _ocrConfidence = picked['confidence'] as double;
    });
  }

  void _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    // Validate anti-duplicate NIK in active rooms (FR-RES-07)
    final allRooms = ref.read(roomListProvider).value ?? [];
    final cleanNik = _nikController.text.trim();
    final duplicate = allRooms.any((r) =>
        r.isOccupied &&
        r.id != widget.room.id &&
        (r.guestNik != null && r.guestNik == cleanNik));

    if (duplicate) {
      setState(() {
        _errorMessage = 'Tamu dengan NIK $cleanNik sedang aktif menginap di kamar lain!';
      });
      return;
    }

    final effectiveTotal = _currentEffectiveTotal;
    final calculatedBasePrice = effectiveTotal / _totalNights;

    try {
      await ref.read(roomListProvider.notifier).checkIn(
            roomId: widget.room.id,
            guestName: _nameController.text.trim(),
            guestNik: cleanNik,
            guestPhone: _phoneController.text.trim(),
            bookingSource: _bookingSource,
            reddoorzBookingCode: _bookingSource == 'REDDOORZ'
                ? _bookingCodeController.text.trim()
                : null,
            totalNights: _totalNights,
            basePrice: calculatedBasePrice,
            paymentMethod: _paymentMethod,
          );

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: AppColors.statusAvailable,
            content: Row(
              children: [
                const Icon(Icons.check_circle_outline, color: Colors.white),
                const SizedBox(width: 8),
                Text(
                  'Check-in Kamar ${widget.room.roomNumber} berhasil! Notifikasi WA pengingat check-out telah dijadwalkan.',
                  style: const TextStyle(color: Colors.white),
                ),
              ],
            ),
          ),
        );
      }
    } catch (e) {
      setState(() {
        _errorMessage = e.toString().replaceAll('Exception: ', '');
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    final isMobile = mediaQuery.size.width < 600;
    final dialogWidth = math.min(720.0, mediaQuery.size.width - (isMobile ? 20 : 48));
    final dialogHeight = math.min(780.0, mediaQuery.size.height * (isMobile ? 0.95 : 0.90));

    final currencyFormatter = NumberFormat.currency(
      locale: 'id_ID',
      symbol: 'Rp ',
      decimalDigits: 0,
    );

    return Dialog(
      insetPadding: EdgeInsets.symmetric(
        horizontal: isMobile ? 10 : 24,
        vertical: isMobile ? 12 : 24,
      ),
      shape: RoundedRectangleBorder(borderRadius: AppRadius.roundedLg),
      backgroundColor: AppColors.surface,
      child: ConstrainedBox(
        constraints: BoxConstraints(maxWidth: dialogWidth, maxHeight: dialogHeight),
        child: Padding(
          padding: EdgeInsets.all(isMobile ? AppSpacing.md : AppSpacing.xl),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Modal Header
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                            decoration: BoxDecoration(
                              color: AppColors.navy100,
                              borderRadius: AppRadius.roundedSm,
                            ),
                            child: Text(
                              'Kamar ${widget.room.roomNumber}',
                              style: AppTypography.h3.copyWith(
                                color: AppColors.navy900,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              'Formulir Check-In Tamu',
                              style: (isMobile ? AppTypography.h3 : AppTypography.h2).copyWith(color: AppColors.navy900),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ],
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close, color: AppColors.textSecondary),
                      onPressed: () => Navigator.of(context).pop(),
                    ),
                  ],
                ),

                const Divider(height: 16),

                Expanded(
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        if (_errorMessage != null) ...[
                          Container(
                            padding: const EdgeInsets.all(AppSpacing.sm),
                            decoration: BoxDecoration(
                              color: AppColors.statusErrorBg,
                              borderRadius: AppRadius.roundedMd,
                            ),
                            child: Text(
                              _errorMessage!,
                              style: AppTypography.caption.copyWith(
                                color: AppColors.statusOccupied,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                          const SizedBox(height: AppSpacing.md),
                        ],

                        // 1. Channel Selector
                        Text(
                          'Kanal Reservasi Pemesanan',
                          style: AppTypography.bodySm.copyWith(fontWeight: FontWeight.w600),
                        ),
                        const SizedBox(height: AppSpacing.xs),
                        Row(
                          children: [
                            Expanded(
                              child: InkWell(
                                onTap: () {
                                  setState(() {
                                    _bookingSource = 'WALK_IN';
                                    if (_paymentMethod == 'REDDOORZ_PREPAID') {
                                      _paymentMethod = 'CASH';
                                    }
                                  });
                                },
                                borderRadius: AppRadius.roundedMd,
                                child: Container(
                                  padding: const EdgeInsets.all(12),
                                  decoration: BoxDecoration(
                                    color: _bookingSource == 'WALK_IN'
                                        ? AppColors.navy100
                                        : AppColors.surface,
                                    border: Border.all(
                                      color: _bookingSource == 'WALK_IN'
                                          ? AppColors.navy700
                                          : AppColors.border,
                                      width: _bookingSource == 'WALK_IN' ? 2 : 1,
                                    ),
                                    borderRadius: AppRadius.roundedMd,
                                  ),
                                  child: Row(
                                    children: [
                                      Icon(
                                        Icons.person_pin_circle_outlined,
                                        color: _bookingSource == 'WALK_IN'
                                            ? AppColors.navy700
                                            : AppColors.textSecondary,
                                      ),
                                      const SizedBox(width: 8),
                                      Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'Walk-in (Offline)',
                                            style: AppTypography.bodySm.copyWith(
                                              fontWeight: FontWeight.w600,
                                              color: _bookingSource == 'WALK_IN'
                                                  ? AppColors.navy900
                                                  : AppColors.textPrimary,
                                            ),
                                          ),
                                          Text(
                                            'Tarif Standar Hotel',
                                            style: AppTypography.caption,
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(width: AppSpacing.md),
                            Expanded(
                              child: InkWell(
                                onTap: () {
                                  setState(() {
                                    _bookingSource = 'REDDOORZ';
                                    _paymentMethod = 'REDDOORZ_PREPAID';
                                  });
                                },
                                borderRadius: AppRadius.roundedMd,
                                child: Container(
                                  padding: const EdgeInsets.all(12),
                                  decoration: BoxDecoration(
                                    color: _bookingSource == 'REDDOORZ'
                                        ? Colors.red.shade50
                                        : AppColors.surface,
                                    border: Border.all(
                                      color: _bookingSource == 'REDDOORZ'
                                          ? Colors.red.shade700
                                          : AppColors.border,
                                      width: _bookingSource == 'REDDOORZ' ? 2 : 1,
                                    ),
                                    borderRadius: AppRadius.roundedMd,
                                  ),
                                  child: Row(
                                    children: [
                                      Icon(
                                        Icons.hotel_class_rounded,
                                        color: _bookingSource == 'REDDOORZ'
                                            ? Colors.red.shade700
                                            : AppColors.textSecondary,
                                      ),
                                      const SizedBox(width: 8),
                                      Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'RedDoorz (Online)',
                                            style: AppTypography.bodySm.copyWith(
                                              fontWeight: FontWeight.w600,
                                              color: _bookingSource == 'REDDOORZ'
                                                  ? Colors.red.shade900
                                                  : AppColors.textPrimary,
                                            ),
                                          ),
                                          Text(
                                            'Wajib Booking Code OTA',
                                            style: AppTypography.caption,
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),

                        if (_bookingSource == 'REDDOORZ') ...[
                          const SizedBox(height: AppSpacing.md),
                          AppTextField(
                            label: 'Kode Booking RedDoorz',
                            hint: 'Contoh: RD-89421',
                            controller: _bookingCodeController,
                            prefixIcon: Icons.confirmation_number_outlined,
                            validator: (v) => (_bookingSource == 'REDDOORZ' &&
                                    (v == null || v.trim().isEmpty))
                                ? 'Kode Booking RedDoorz wajib diisi'
                                : null,
                          ),
                        ],

                        const SizedBox(height: AppSpacing.lg),

                        // 2. OCR Section
                        Container(
                          padding: const EdgeInsets.all(AppSpacing.md),
                          decoration: BoxDecoration(
                            color: AppColors.bg,
                            borderRadius: AppRadius.roundedMd,
                            border: Border.all(color: AppColors.border),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Row(
                                    children: [
                                      const Icon(
                                        Icons.document_scanner_rounded,
                                        color: AppColors.navy700,
                                        size: 20,
                                      ),
                                      const SizedBox(width: 8),
                                      Text(
                                        'Ekstraksi Kamera / OCR KTP Tamu',
                                        style: AppTypography.bodySm.copyWith(
                                          fontWeight: FontWeight.w700,
                                          color: AppColors.navy900,
                                        ),
                                      ),
                                    ],
                                  ),
                                  if (_isOcrExtracted)
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 8,
                                        vertical: 2,
                                      ),
                                      decoration: BoxDecoration(
                                        color: AppColors.statusSuccessBg,
                                        borderRadius: AppRadius.roundedSm,
                                      ),
                                      child: Text(
                                        'Akurasi: ${(_ocrConfidence * 100).toInt()}% (Tinggi)',
                                        style: AppTypography.overline.copyWith(
                                          color: const Color(0xFF16A34A),
                                          fontWeight: FontWeight.w700,
                                        ),
                                      ),
                                    ),
                                ],
                              ),
                              const SizedBox(height: 6),
                              Text(
                                'Pindai KTP untuk mengisi NIK, Nama, dan Alamat secara otomatis (< 2 detik) guna mempercepat antrean.',
                                style: AppTypography.caption,
                              ),
                              const SizedBox(height: AppSpacing.sm),
                              Wrap(
                                crossAxisAlignment: WrapCrossAlignment.center,
                                spacing: AppSpacing.md,
                                runSpacing: AppSpacing.xs,
                                children: [
                                  AppButton(
                                    label: _isOcrExtracted ? 'Scan Ulang KTP' : 'Scan KTP Sekarang',
                                    variant: AppButtonVariant.secondary,
                                    icon: Icons.camera_alt_outlined,
                                    isLoading: _isOcrLoading,
                                    onPressed: _simulateOcrScan,
                                  ),
                                  Text(
                                    'Atau ketik langsung formulir di bawah',
                                    style: AppTypography.caption,
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),

                        const SizedBox(height: AppSpacing.lg),

                        // Guest Data Fields - Responsive layout
                        if (isMobile) ...[
                          AppTextField(
                            label: 'NIK KTP (16 Digit)',
                            hint: '16 digit angka KTP',
                            controller: _nikController,
                            isAutoFilled: _isOcrExtracted,
                            prefixIcon: Icons.badge_outlined,
                            keyboardType: TextInputType.number,
                            validator: (v) {
                              if (v == null || v.trim().isEmpty) return 'NIK wajib diisi';
                              if (v.trim().length != 16) return 'NIK harus tepat 16 digit';
                              return null;
                            },
                          ),
                          const SizedBox(height: AppSpacing.sm),
                          AppTextField(
                            label: 'Nama Tamu (KTP)',
                            hint: 'Sesuai kartu identitas',
                            controller: _nameController,
                            isAutoFilled: _isOcrExtracted,
                            prefixIcon: Icons.person_outline,
                            validator: (v) =>
                                (v == null || v.trim().isEmpty) ? 'Nama wajib diisi' : null,
                          ),
                          const SizedBox(height: AppSpacing.sm),
                          AppTextField(
                            label: 'Nomor WhatsApp Tamu',
                            hint: '08... atau +62... (untuk pengingat check-out)',
                            controller: _phoneController,
                            prefixIcon: Icons.chat_bubble_outline,
                            keyboardType: TextInputType.phone,
                            validator: (v) {
                              if (v == null || v.trim().isEmpty) {
                                return 'Nomor WhatsApp wajib diisi';
                              }
                              final clean = v.trim();
                              if (!clean.startsWith('08') && !clean.startsWith('+62')) {
                                return 'Format harus diawali 08... atau +62...';
                              }
                              return null;
                            },
                          ),
                          const SizedBox(height: AppSpacing.sm),
                          AppTextField(
                            label: 'Alamat Domisili (KTP)',
                            hint: 'Kota / Alamat lengkap',
                            controller: _addressController,
                            isAutoFilled: _isOcrExtracted,
                            prefixIcon: Icons.location_on_outlined,
                          ),
                        ] else ...[
                          Row(
                            children: [
                              Expanded(
                                child: AppTextField(
                                  label: 'NIK KTP (16 Digit)',
                                  hint: '16 digit angka KTP',
                                  controller: _nikController,
                                  isAutoFilled: _isOcrExtracted,
                                  prefixIcon: Icons.badge_outlined,
                                  keyboardType: TextInputType.number,
                                  validator: (v) {
                                    if (v == null || v.trim().isEmpty) return 'NIK wajib diisi';
                                    if (v.trim().length != 16) return 'NIK harus tepat 16 digit';
                                    return null;
                                  },
                                ),
                              ),
                              const SizedBox(width: AppSpacing.md),
                              Expanded(
                                child: AppTextField(
                                  label: 'Nama Tamu (KTP)',
                                  hint: 'Sesuai kartu identitas',
                                  controller: _nameController,
                                  isAutoFilled: _isOcrExtracted,
                                  prefixIcon: Icons.person_outline,
                                  validator: (v) =>
                                      (v == null || v.trim().isEmpty) ? 'Nama wajib diisi' : null,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: AppSpacing.md),
                          Row(
                            children: [
                              Expanded(
                                child: AppTextField(
                                  label: 'Nomor WhatsApp Tamu',
                                  hint: '08... atau +62... (untuk pengingat check-out)',
                                  controller: _phoneController,
                                  prefixIcon: Icons.chat_bubble_outline,
                                  keyboardType: TextInputType.phone,
                                  validator: (v) {
                                    if (v == null || v.trim().isEmpty) {
                                      return 'Nomor WhatsApp wajib diisi';
                                    }
                                    final clean = v.trim();
                                    if (!clean.startsWith('08') && !clean.startsWith('+62')) {
                                      return 'Format harus diawali 08... atau +62...';
                                    }
                                    return null;
                                  },
                                ),
                              ),
                              const SizedBox(width: AppSpacing.md),
                              Expanded(
                                child: AppTextField(
                                  label: 'Alamat Domisili (KTP)',
                                  hint: 'Kota / Alamat lengkap',
                                  controller: _addressController,
                                  isAutoFilled: _isOcrExtracted,
                                  prefixIcon: Icons.location_on_outlined,
                                ),
                              ),
                            ],
                          ),
                        ],

                        const SizedBox(height: AppSpacing.lg),

                        // Stay Duration & Payment - Modern Quick Flow
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // 1. Duration Section
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Flexible(
                                  child: Text(
                                    'Durasi Menginap',
                                    style: AppTypography.bodySm.copyWith(
                                      fontWeight: FontWeight.w700,
                                    ),
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(
                                    color: AppColors.navy50,
                                    borderRadius: BorderRadius.circular(6),
                                    border: Border.all(color: AppColors.border),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      const Icon(Icons.event_available_rounded, size: 13, color: AppColors.navy700),
                                      const SizedBox(width: 4),
                                      Text(
                                        'Out: ${DateFormat('EEE, d MMM', 'id').format(DateTime.now().add(Duration(days: _totalNights)))} pk 12:00 WIB',
                                        style: const TextStyle(
                                          fontSize: 11.5,
                                          fontWeight: FontWeight.w700,
                                          color: AppColors.navy900,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: AppSpacing.xs),
                            Wrap(
                              spacing: 8,
                              runSpacing: 6,
                              crossAxisAlignment: WrapCrossAlignment.center,
                              children: [
                                // Stepper
                                Container(
                                  decoration: BoxDecoration(
                                    color: AppColors.surface,
                                    borderRadius: BorderRadius.circular(8),
                                    border: Border.all(color: AppColors.border),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      IconButton(
                                        icon: const Icon(Icons.remove, size: 16),
                                        padding: const EdgeInsets.all(6),
                                        constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
                                        onPressed: _totalNights > 1
                                            ? () => _setNights(_totalNights - 1)
                                            : null,
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.symmetric(horizontal: 8),
                                        child: Text(
                                          '$_totalNights Malam',
                                          style: AppTypography.bodySm.copyWith(
                                            fontWeight: FontWeight.w800,
                                            color: AppColors.navy900,
                                          ),
                                        ),
                                      ),
                                      IconButton(
                                        icon: const Icon(Icons.add, size: 16),
                                        padding: const EdgeInsets.all(6),
                                        constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
                                        onPressed: () => _setNights(_totalNights + 1),
                                      ),
                                    ],
                                  ),
                                ),

                                // Quick presets
                                _buildNightChip(1, '1 Malam (Standar)'),
                                _buildNightChip(2, '2 Malam'),
                                _buildNightChip(3, '3 Malam'),
                                _buildNightChip(7, '7 Malam (1 Minggu)'),
                              ],
                            ),

                            const SizedBox(height: AppSpacing.md),

                            // 2. Payment Method Modern Pills
                            Text(
                              'Metode Pembayaran',
                              style: AppTypography.bodySm.copyWith(
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                            const SizedBox(height: AppSpacing.xs),
                            Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              children: [
                                if (_bookingSource == 'REDDOORZ')
                                  _buildPaymentPill(
                                    id: 'REDDOORZ_PREPAID',
                                    label: 'Lunas RedDoorz App',
                                    icon: Icons.hotel_class_rounded,
                                    activeColor: const Color(0xFFDC2626),
                                    activeBg: const Color(0xFFFEE2E2),
                                  ),
                                _buildPaymentPill(
                                  id: 'CASH',
                                  label: 'Tunai (Cash)',
                                  icon: Icons.payments_outlined,
                                  activeColor: AppColors.navy900,
                                  activeBg: AppColors.navy100,
                                ),
                                _buildPaymentPill(
                                  id: 'QRIS',
                                  label: 'QRIS Dinamis',
                                  icon: Icons.qr_code_rounded,
                                  activeColor: const Color(0xFF047857),
                                  activeBg: const Color(0xFFD1FAE5),
                                ),
                                _buildPaymentPill(
                                  id: 'TRANSFER',
                                  label: 'Transfer Bank (BCA/Mandiri)',
                                  icon: Icons.account_balance_outlined,
                                  activeColor: const Color(0xFF1D4ED8),
                                  activeBg: const Color(0xFFDBEAFE),
                                ),
                              ],
                            ),
                          ],
                        ),

                        const SizedBox(height: AppSpacing.lg),

                        // Interactive Manual / Dynamic Price Editor Card
                        Container(
                          padding: const EdgeInsets.all(AppSpacing.md),
                          decoration: BoxDecoration(
                            color: _isManualPrice ? const Color(0xFFFFFBEB) : AppColors.navy50,
                            borderRadius: AppRadius.roundedMd,
                            border: Border.all(
                              color: _isManualPrice ? const Color(0xFFF59E0B) : AppColors.border,
                              width: _isManualPrice ? 1.5 : 1,
                            ),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Flexible(
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Flexible(
                                          child: Text(
                                            'Total Biaya Menginap',
                                            style: AppTypography.bodySm.copyWith(
                                              fontWeight: FontWeight.w700,
                                              color: AppColors.navy900,
                                            ),
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        if (_isManualPrice)
                                          Container(
                                            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                            decoration: BoxDecoration(
                                              color: const Color(0xFFFDE68A),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                            child: const Text(
                                              'Tarif Manual / Khusus',
                                              style: TextStyle(
                                                fontSize: 10,
                                                fontWeight: FontWeight.bold,
                                                color: Color(0xFFB45309),
                                              ),
                                            ),
                                          )
                                        else
                                          Container(
                                            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                            decoration: BoxDecoration(
                                              color: AppColors.navy100,
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                            child: const Text(
                                              'Standar Otomatis',
                                              style: TextStyle(
                                                fontSize: 10,
                                                fontWeight: FontWeight.bold,
                                                color: AppColors.navy700,
                                              ),
                                            ),
                                          ),
                                      ],
                                    ),
                                  ),
                                  if (_isManualPrice)
                                    TextButton.icon(
                                      style: TextButton.styleFrom(
                                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                        visualDensity: VisualDensity.compact,
                                      ),
                                      icon: const Icon(Icons.restart_alt_rounded, size: 14),
                                      label: const Text('Reset ke Standar', style: TextStyle(fontSize: 11)),
                                      onPressed: _resetPriceToStandard,
                                    ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              if (isMobile) ...[
                                TextField(
                                  controller: _priceController,
                                  keyboardType: TextInputType.number,
                                  inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                                  style: AppTypography.h2.copyWith(
                                    fontWeight: FontWeight.w800,
                                    color: _isManualPrice ? const Color(0xFFB45309) : AppColors.navy900,
                                  ),
                                  onChanged: (val) {
                                    setState(() {
                                      _isManualPrice = true;
                                    });
                                  },
                                  decoration: InputDecoration(
                                    prefixText: 'Rp ',
                                    prefixStyle: AppTypography.h2.copyWith(
                                      fontWeight: FontWeight.w800,
                                      color: _isManualPrice ? const Color(0xFFB45309) : AppColors.navy900,
                                    ),
                                    filled: true,
                                    fillColor: Colors.white,
                                    isDense: true,
                                    contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(8),
                                      borderSide: BorderSide(color: AppColors.border),
                                    ),
                                    enabledBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(8),
                                      borderSide: BorderSide(
                                        color: _isManualPrice ? const Color(0xFFF59E0B) : AppColors.border,
                                      ),
                                    ),
                                    focusedBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(8),
                                      borderSide: const BorderSide(color: AppColors.navy900, width: 1.5),
                                    ),
                                  ),
                                ),
                                const SizedBox(height: AppSpacing.sm),
                                Row(
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  children: [
                                    Text(
                                      'Standar: ${currencyFormatter.format(widget.room.basePricePerNight)}/malam',
                                      style: AppTypography.caption.copyWith(color: AppColors.textSecondary),
                                    ),
                                    Text(
                                      'Total: ${currencyFormatter.format(widget.room.basePricePerNight * _totalNights)}',
                                      style: AppTypography.caption.copyWith(
                                        fontWeight: FontWeight.w700,
                                        color: AppColors.navy700,
                                      ),
                                    ),
                                  ],
                                ),
                              ] else
                                Row(
                                  children: [
                                    Expanded(
                                      flex: 3,
                                      child: TextField(
                                        controller: _priceController,
                                        keyboardType: TextInputType.number,
                                        inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                                        style: AppTypography.h2.copyWith(
                                          fontWeight: FontWeight.w800,
                                          color: _isManualPrice ? const Color(0xFFB45309) : AppColors.navy900,
                                        ),
                                        onChanged: (val) {
                                          setState(() {
                                            _isManualPrice = true;
                                          });
                                        },
                                        decoration: InputDecoration(
                                          prefixText: 'Rp ',
                                          prefixStyle: AppTypography.h2.copyWith(
                                            fontWeight: FontWeight.w800,
                                            color: _isManualPrice ? const Color(0xFFB45309) : AppColors.navy900,
                                          ),
                                          filled: true,
                                          fillColor: Colors.white,
                                          isDense: true,
                                          contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                                          border: OutlineInputBorder(
                                            borderRadius: BorderRadius.circular(8),
                                            borderSide: BorderSide(color: AppColors.border),
                                          ),
                                          enabledBorder: OutlineInputBorder(
                                            borderRadius: BorderRadius.circular(8),
                                            borderSide: BorderSide(
                                              color: _isManualPrice ? const Color(0xFFF59E0B) : AppColors.border,
                                            ),
                                          ),
                                          focusedBorder: OutlineInputBorder(
                                            borderRadius: BorderRadius.circular(8),
                                            borderSide: const BorderSide(color: AppColors.navy900, width: 1.5),
                                          ),
                                        ),
                                      ),
                                    ),
                                    const SizedBox(width: AppSpacing.md),
                                    Expanded(
                                      flex: 2,
                                      child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'Tarif Standar Unit:',
                                            style: AppTypography.caption.copyWith(color: AppColors.textSecondary),
                                          ),
                                          Text(
                                            '${currencyFormatter.format(widget.room.basePricePerNight)} / malam',
                                            style: AppTypography.bodySm.copyWith(fontWeight: FontWeight.w600),
                                          ),
                                          Text(
                                            'Total Standar: ${currencyFormatter.format(widget.room.basePricePerNight * _totalNights)}',
                                            style: AppTypography.caption.copyWith(color: AppColors.textSecondary),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              const SizedBox(height: 4),
                              Text(
                                '💡 Nominal di atas dapat diubah manual secara bebas untuk diskon khusus, promo offline, atau negosiasi harga kamar.',
                                style: TextStyle(
                                  fontSize: 11,
                                  fontStyle: FontStyle.italic,
                                  color: _isManualPrice ? const Color(0xFF92400E) : AppColors.textSecondary,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),

                const Divider(height: 16),

                // Modal Footer - Responsive Wrap
                Wrap(
                  alignment: WrapAlignment.end,
                  crossAxisAlignment: WrapCrossAlignment.center,
                  spacing: AppSpacing.sm,
                  runSpacing: AppSpacing.sm,
                  children: [
                    AppButton(
                      label: 'Batal',
                      variant: AppButtonVariant.outline,
                      onPressed: () => Navigator.of(context).pop(),
                    ),
                    // Exactly ONE primary orange CTA per design.md rules
                    AppButton(
                      label: 'Simpan & Check-In Tamu',
                      variant: AppButtonVariant.primary,
                      icon: Icons.check_circle_outline_rounded,
                      onPressed: _handleSubmit,
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildNightChip(int nights, String label) {
    final isSelected = _totalNights == nights;
    return InkWell(
      onTap: () => _setNights(nights),
      borderRadius: BorderRadius.circular(8),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6.5),
        decoration: BoxDecoration(
          color: isSelected ? AppColors.navy900 : AppColors.surface,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: isSelected ? AppColors.navy900 : AppColors.border,
            width: isSelected ? 1.5 : 1,
          ),
        ),
        child: Text(
          label,
          style: TextStyle(
            fontSize: 12.5,
            fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
            color: isSelected ? Colors.white : AppColors.textPrimary,
          ),
        ),
      ),
    );
  }

  Widget _buildPaymentPill({
    required String id,
    required String label,
    required IconData icon,
    required Color activeColor,
    required Color activeBg,
  }) {
    final isSelected = _paymentMethod == id;
    return InkWell(
      onTap: () => setState(() => _paymentMethod = id),
      borderRadius: BorderRadius.circular(8),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: isSelected ? activeBg : AppColors.surface,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: isSelected ? activeColor : AppColors.border,
            width: isSelected ? 1.5 : 1,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              icon,
              size: 16,
              color: isSelected ? activeColor : AppColors.textSecondary,
            ),
            const SizedBox(width: 6),
            Text(
              label,
              style: TextStyle(
                fontSize: 12.5,
                fontWeight: isSelected ? FontWeight.w700 : FontWeight.w600,
                color: isSelected ? activeColor : AppColors.textPrimary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
